[project]
name = "twitch-dj-clipper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    'pyyaml>=6.0.3',
    "requests>=2.32.5",
    "werkzeug>=3.1.5",
]
