bot_name: 'the username of your bot account all lowercase' 
oath_token: 'your_oath_token' #generated on first run of the script by following instructions in the terminal
channel: 'the username of the channel the bot should join all lowercase'
twitch_api_id: "your twitch api id"
twitch_api_secret: "your twitch api secret"
clip_start_before_timestamp: 90 #seconds, the amount of time to go back from the created timestamp to set the start of the clip
total_clip_duration: 180 #seconds, the total time in second of how long you want your final clip to be
metadata_artist: twitch_dj_clipper #name added to the clip files metadata
vod_folder_path: "/path/to/your/vods/folder" #path to your vods folder used for generating clips with the latest files automagicly
allow_stick: True # wether or not to allow the !stick command, a small easter egg wich returns a "<username> has a <random> cm stick"